apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/nats-depl.yaml
build: 
  local: 
    push: false
  #googleCloudBuild:
  #  projectId: ticketing-dev-444518
