apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build: 
  local: 
    push: false
  #googleCloudBuild:
  #  projectId: ticketing-dev-444518
  artifacts:
    - image: thorstenneff/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: '.'
    - image: thorstenneff/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '**/*.js'
            dest: '.'
    - image: thorstenneff/tickets
      context: tickets
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: '.'
