apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tickets-depl
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: tickets
  template: 
    metadata: 
      labels: 
        app: tickets
    spec:
      containers:
        - name: tickets
          image: us.gcr.io/ticketing-dev-444518/tickets
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: "gke_ticketing-dev-444518_europe-west1-b_ticketing-dev"
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY


---
apiVersion: v1
kind: Service
metadata: 
  name: tickets-srv
spec:
  selector: 
    app: tickets
  ports: 
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000